-- Seed: editierbares Oktoberfest-Sondermenü ("Besondere Anlässe")
-- Generiert von scripts/gen-oktoberfest-menu.ts aus src/translations/*
-- Idempotent: legt das Menü nur an, wenn Slug 'oktoberfest-menue' noch nicht existiert.
DO $$
DECLARE m_id uuid; c_id uuid;
BEGIN
  IF EXISTS (SELECT 1 FROM public.menus WHERE slug = 'oktoberfest-menue') THEN
    RAISE NOTICE 'Oktoberfest-Menü existiert bereits – übersprungen.';
    RETURN;
  END IF;

  INSERT INTO public.menus (menu_type, title, title_en, title_it, title_fr, subtitle, subtitle_en, subtitle_it, subtitle_fr, slug, slug_en, slug_it, slug_fr, is_published, published_at, sort_order)
  VALUES ('special', 'Oktoberfest – Speisen & Getränke', 'Oktoberfest – Food & Drinks', 'Oktoberfest – Cibo & Bevande', 'Oktoberfest – Cuisine & Boissons', 'Bayerisch-italienische Freundschaft zur Wiesn-Zeit', 'Bavarian-Italian friendship for Oktoberfest Munich', 'Amicizia bavarese-italiana al tempo della Wiesn (Oktoberfest)', 'L''amitié bavaroise-italienne au temps de la Wiesn', 'oktoberfest-menue', 'oktoberfest-menu', 'oktoberfest-menu-it', 'oktoberfest-menu-fr', true, now(), 150)
  RETURNING id INTO m_id;

  INSERT INTO public.menu_categories (menu_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, sort_order)
  VALUES (m_id, '🍺 Wiesnbier vom Holzfass (Maß)', '🍺 Wiesnbier from the wooden cask (Maß)', '🍺 Wiesnbier (birra dell''Oktoberfest) dalla botte di legno (Maß)', '🍺 Bière de la Wiesn au fût de bois (Maß)', 'Bei uns kommt echtes Wiesnbier ins Glas: Paulaner Festbier frisch aus dem Holzfass – als Maß. Dazu unsere italienische Aperitivo-Brücke.', 'Real Wiesnbier in your glass: Paulaner Festbier fresh from the wooden cask – as a Maß. Plus our Italian aperitivo bridge.', 'Da noi nel bicchiere arriva vera Wiesnbier: Paulaner Festbier fresca dalla botte di legno – come Maß (boccale da 1 litro). In più il nostro ponte aperitivo italiano.', 'Chez nous, c''est de la vraie bière de la Wiesn dans le verre: la Festbier Paulaner fraîchement tirée du fût de bois – en Maß. Avec notre passerelle aperitivo à l''italienne.', 1)
  RETURNING id INTO c_id;
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Paulaner Wiesnbier – Maß (1 l)', 'Paulaner Wiesnbier – Maß (1 l)', 'Paulaner Wiesnbier – Maß (1 l)', 'Bière de la Wiesn Paulaner – Maß (1 l)', 'Echtes Wiesn-Festbier von Paulaner, frisch aus dem Holzfass gezapft – süffig, vollmundig, festlich. Die Maß zum Vorglühen.', 'Real Wiesn Festbier by Paulaner, freshly tapped from the wooden cask – smooth, full-bodied, festive. The Maß for the warm-up.', 'Vera Festbier dell''Oktoberfest di Paulaner, spillata fresca dalla botte di legno – bevibile, piena e festosa. La Maß per il pre-Wiesn.', 'Vraie Festbier de la Wiesn de Paulaner, fraîchement tirée du fût de bois – désaltérante, ronde, festive. La Maß pour se mettre en jambes.', '€ 12,90', '€ 12,90', '€ 12,90', '€ 12,90', 1);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Radler – Maß (1 l)', 'Radler – Maß (1 l)', 'Radler – Maß (1 l)', 'Radler – Maß (1 l)', 'Wiesnbier mit Zitronenlimonade – leicht und erfrischend, ebenfalls als Maß.', 'Wiesnbier with lemonade – light and refreshing, also as a Maß.', 'Wiesnbier (birra dell''Oktoberfest) con limonata al limone – leggera e dissetante, anch''essa come Maß.', 'Bière de la Wiesn avec limonade au citron – légère et rafraîchissante, également en Maß.', '€ 12,90', '€ 12,90', '€ 12,90', '€ 12,90', 2);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Russn – Maß (1 l)', 'Russn – Maß (1 l)', 'Russn – Maß (1 l)', 'Russn – Maß (1 l)', 'Helles Weißbier mit Zitronenlimo – spritzig und unkompliziert, als Maß.', 'Pale wheat beer with lemonade – sparkling and easygoing, as a Maß.', 'Weißbier chiara con limonata al limone – frizzante e semplice, come Maß.', 'Bière blanche claire avec limonade au citron – pétillante et sans chichi, en Maß.', '€ 12,90', '€ 12,90', '€ 12,90', '€ 12,90', 3);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Alkoholfreies Weißbier', 'Alcohol-free wheat beer', 'Weißbier analcolica', 'Bière blanche sans alcool', 'Voller Geschmack, ohne Alkohol – ideal, wenn ihr noch fahrt oder einfach genießen möchtet.', 'Full flavour, without the alcohol – ideal if you''re still driving or simply want to enjoy.', 'Gusto pieno, senza alcol – ideale se dovete ancora guidare o semplicemente volete godervi il momento.', 'Tout le goût, sans alcool – idéale si vous prenez encore la route ou voulez simplement profiter.', '€ 6,90', '€ 6,90', '€ 6,90', '€ 6,90', 4);

  INSERT INTO public.menu_categories (menu_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, sort_order)
  VALUES (m_id, '🥂 Bayerisch-italienische Aperitivo-Brücke', '🥂 Bavarian-Italian aperitivo bridge', '🥂 Ponte aperitivo bavarese-italiano', '🥂 La passerelle aperitivo bavaroise-italienne', NULL, NULL, NULL, NULL, 2)
  RETURNING id INTO c_id;
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Bavarese Spritz', 'Bavarese Spritz', 'Bavarese Spritz', 'Bavarese Spritz', 'Unsere Haus-Idee zur Wiesn: Aperol, Prosecco und ein bayerischer Twist – Bayern trifft Venetien im Glas.', 'Our house idea for the Wiesn: Aperol, Prosecco and a Bavarian twist – Bavaria meets the Veneto in a glass.', 'La nostra idea della casa per la Wiesn: Aperol, Prosecco e un tocco bavarese – la Baviera incontra il Veneto nel bicchiere.', 'Notre création maison pour la Wiesn: Aperol, Prosecco et une touche bavaroise – la Bavière rencontre la Vénétie dans le verre.', '€ 9,90', '€ 9,90', '€ 9,90', '€ 9,90', 1);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Aperol Spritz', 'Aperol Spritz', 'Aperol Spritz', 'Aperol Spritz', 'Der italienische Klassiker – Aperol, Prosecco, Soda, Orange. Die perfekte Einstimmung.', 'The Italian classic – Aperol, Prosecco, soda, orange. The perfect way to get in the mood.', 'Il classico italiano – Aperol, Prosecco, soda, arancia. L''introduzione perfetta.', 'Le classique italien – Aperol, Prosecco, soda, orange. La mise en bouche parfaite.', '€ 9,90', '€ 9,90', '€ 9,90', '€ 9,90', 2);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Hugo', 'Hugo', 'Hugo', 'Hugo', 'Fruchtig-frisch mit Holunder, Prosecco, Soda und Minze.', 'Fruity and fresh with elderflower, Prosecco, soda and mint.', 'Fruttato e fresco con sambuco, Prosecco, soda e menta.', 'Fruité et frais avec fleur de sureau, Prosecco, soda et menthe.', '€ 9,90', '€ 9,90', '€ 9,90', '€ 9,90', 3);

  INSERT INTO public.menu_categories (menu_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, sort_order)
  VALUES (m_id, '🥨 Brotzeit & Brezn – die Bavarese Bretter', '🥨 Brotzeit & Brezn – the Bavarese boards', '🥨 Brotzeit & Brezn (bretzel) – i taglieri Bavarese', '🥨 Brotzeit & Brezn – les planches Bavarese', 'Zünftig teilen und genießen: bayerische Brotzeit, kombiniert mit italienischen Spezialitäten – ideal für Gruppen, zum Mittag oder als Vorspeise.', 'Share and enjoy in true Wiesn style: Bavarian Brotzeit combined with Italian specialities – ideal for groups, as a lunch or a starter.', 'Da condividere e gustare in compagnia: Brotzeit bavarese, combinata con specialità italiane – ideale per gruppi, a pranzo o come antipasto.', 'À partager et à savourer à la bonne franquette: brotzeit bavaroise, associée à des spécialités italiennes – idéale pour les groupes, en plat de midi ou en entrée.', 3)
  RETURNING id INTO c_id;
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Bavarese-Brett (für 2–4)', 'Bavarese board (for 2–4)', 'Tagliere Bavarese (per 2–4)', 'Planche Bavarese (pour 2 à 4)', 'Das Herzstück: Obatzda & Burrata, Brezn & Grissini, italienische Salumi & bayerischer Aufschnitt, Radi, eingelegtes Gemüse und Oliven.', 'The centrepiece: Obatzda & Burrata, Brezn & Grissini, Italian salumi & Bavarian cold cuts, radish, pickled vegetables and olives.', 'Il cuore: Obatzda & Burrata, Brezn (bretzel) & Grissini, salumi italiani & affettati bavaresi, ravanello, verdure sott''aceto e olive.', 'La pièce maîtresse: Obatzda & Burrata, Brezn & Grissini, Salumi italiens & charcuterie bavaroise, radis, légumes marinés et olives.', 'ca. € 24,90', 'ca. € 24,90', 'ca. € 24,90', 'ca. € 24,90', 1);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Brett München', 'Munich board', 'Tagliere Monaco', 'Planche Munich', 'Klassisch bayerisch: Obatzda, Weißwurst, Brezn, süßer Senf und Radi.', 'Classically Bavarian: Obatzda, Weißwurst, Brezn (pretzels), sweet mustard and radish.', 'Classico bavarese: Obatzda, Weißwurst, Brezn (bretzel), senape dolce e ravanello.', 'Classique bavarois: Obatzda, Weißwurst, Brezn, moutarde douce et radis.', 'ca. € 19,90', 'ca. € 19,90', 'ca. € 19,90', 'ca. € 19,90', 2);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Brett Italia', 'Italia board', 'Tagliere Italia', 'Planche Italia', 'Italienisch fein: Burrata, Mortadella, Salami, Grissini und marinierte Antipasti.', 'Finely Italian: Burrata, Mortadella, Salami, Grissini and marinated antipasti.', 'Finezza italiana: Burrata, Mortadella, salame, Grissini e antipasti marinati.', 'Finesse italienne: Burrata, Mortadella, Salami, Grissini et antipasti marinés.', 'ca. € 19,90', 'ca. € 19,90', 'ca. € 19,90', 'ca. € 19,90', 3);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Frische Brezn', 'Fresh Brezn', 'Brezn (bretzel) fresche', 'Brezn frais', 'Original bayerische Brezn, frisch gebacken – mit Butter oder Obatzda.', 'Original Bavarian Brezn (pretzel), freshly baked – with butter or Obatzda.', 'Brezn (bretzel) bavaresi originali, appena sfornate – con burro o Obatzda.', 'Authentiques Brezn bavarois, fraîchement cuits – au beurre ou avec Obatzda.', '€ 4,50', '€ 4,50', '€ 4,50', '€ 4,50', 4);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Obatzda', 'Obatzda', 'Obatzda', 'Obatzda', 'Hausgemachter Obatzda mit Brezn – der bayerische Brotzeit-Klassiker.', 'Homemade Obatzda with Brezn (pretzel) – the Bavarian Brotzeit classic.', 'Obatzda fatto in casa con Brezn (bretzel) – il classico bavarese della Brotzeit.', 'Obatzda maison avec Brezn – le classique de la brotzeit bavaroise.', '€ 8,90', '€ 8,90', '€ 8,90', '€ 8,90', 5);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Weißwurst-Paar', 'Weißwurst pair', 'Coppia di Weißwurst', 'Paire de Weißwurst', 'Zwei Münchner Weißwürste mit süßem Senf und Brezn.', 'Two Munich Weißwurst with sweet mustard and Brezn (pretzel).', 'Due Weißwurst di Monaco con senape dolce e Brezn (bretzel).', 'Deux Weißwurst munichoises avec moutarde douce et Brezn.', '€ 8,90', '€ 8,90', '€ 8,90', '€ 8,90', 6);

  INSERT INTO public.menu_categories (menu_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, sort_order)
  VALUES (m_id, '🍕 Oktoberfest-Pizzen – 2 bayerisch, 2 italienisch', '🍕 Oktoberfest pizzas – 2 Bavarian, 2 Italian', '🍕 Pizze dell''Oktoberfest – 2 bavaresi, 2 italiane', '🍕 Pizzas Oktoberfest – 2 bavaroises, 2 italiennes', 'Unsere neapolitanische Pizza zur Wiesn neu gedacht: zwei bayerische und zwei italienische Special-Pizzen – die bayerisch-italienische Freundschaft auf dem Teller.', 'Our Neapolitan pizza reimagined for the Wiesn: two Bavarian and two Italian special pizzas – Bavarian-Italian friendship on a plate.', 'La nostra pizza napoletana ripensata per la Wiesn: due pizze speciali bavaresi e due italiane – l''amicizia bavarese-italiana nel piatto.', 'Notre pizza napolitaine repensée pour la Wiesn: deux pizzas spéciales bavaroises et deux italiennes – l''amitié bavaroise-italienne dans l''assiette.', 4)
  RETURNING id INTO c_id;
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Pizza Bratwurst & Pommes', 'Pizza Bratwurst & fries', 'Pizza Bratwurst & patatine', 'Pizza Bratwurst & frites', 'Frech und herzhaft: bayerische Bratwurst, Pommes und Senf auf neapolitanischem Teig.', 'Cheeky and hearty: Bavarian Bratwurst, fries and mustard on Neapolitan dough.', 'Sfiziosa e saporita: Bratwurst bavarese, patatine e senape su impasto napoletano.', 'Espiègle et savoureuse: saucisse bavaroise (Bratwurst), frites et moutarde sur pâte napolitaine.', 'ca. € 15,90', 'ca. € 15,90', 'ca. € 15,90', 'ca. € 15,90', 1);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Pizza Kartoffel-Carpaccio & Spanferkel', 'Pizza potato carpaccio & suckling pig', 'Pizza Carpaccio di patate & maialino', 'Pizza carpaccio de pomme de terre & cochon de lait', 'Dünn gehobelte Kartoffel, zartes Spanferkel und Rosmarin – deftig und besonders.', 'Thinly shaved potato, tender suckling pig and rosemary – hearty and special.', 'Patate affettate sottili, tenero maialino e rosmarino – sostanziosa e particolare.', 'Fines lamelles de pomme de terre, tendre cochon de lait et romarin – consistante et originale.', 'ca. € 16,90', 'ca. € 16,90', 'ca. € 16,90', 'ca. € 16,90', 2);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Pizza Salami piccante', 'Pizza Salami piccante', 'Pizza Salami piccante', 'Pizza Salami piccante', 'Italienischer Klassiker: pikante italienische Salami, San-Marzano-Tomate und Mozzarella.', 'An Italian classic: spicy Italian salami, San Marzano tomato and mozzarella.', 'Classico italiano: Salami piccante italiano, pomodoro San Marzano e mozzarella.', 'Classique italien: salami italien piquant, tomate San Marzano et mozzarella.', 'ca. € 14,90', 'ca. € 14,90', 'ca. € 14,90', 'ca. € 14,90', 3);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Pizza Obatzda & Cime di Rapa', 'Pizza Obatzda & Cime di Rapa', 'Pizza Obatzda & Cime di Rapa', 'Pizza Obatzda & Cime di Rapa', 'Die Fusion: cremiger Obatzda trifft italienische Cime di Rapa (Friarielli) – bayerisch-italienisch vereint.', 'The fusion: creamy Obatzda meets Italian Cime di Rapa (friarielli) – Bavarian and Italian united.', 'La fusione: cremoso Obatzda incontra le Cime di Rapa (Friarielli) italiane – bavarese-italiano uniti.', 'La fusion: l''Obatzda crémeux rencontre les Cime di Rapa italiennes (Friarielli) – bavarois-italien réunis.', 'ca. € 14,90', 'ca. € 14,90', 'ca. € 14,90', 'ca. € 14,90', 4);

  INSERT INTO public.menu_categories (menu_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, sort_order)
  VALUES (m_id, '🍖 Braten & Hauptgerichte', '🍖 Roasts & main courses', '🍖 Arrosti & secondi', '🍖 Rôtis & plats principaux', 'Herzhaft bayerisch mit italienischer Note – als zusätzliche Wiesn-Spezialitäten zur normalen Karte.', 'Hearty and Bavarian with an Italian touch – as additional Wiesn specialities alongside the regular menu.', 'Saporiti alla bavarese con nota italiana – come specialità aggiuntive della Wiesn rispetto alla carta normale.', 'Du savoureux bavarois avec une touche italienne – des spécialités supplémentaires de la Wiesn, en plus de la carte habituelle.', 5)
  RETURNING id INTO c_id;
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Schweinsbraten', 'Schweinsbraten', 'Schweinsbraten', 'Schweinsbraten', 'Zarter Schweinsbraten mit knuspriger Kruste und Dunkelbier-Jus, dazu Knödel oder Polenta.', 'Tender Schweinsbraten with crispy crackling and dark-beer jus, served with dumplings or polenta.', 'Tenero Schweinsbraten con crosta croccante e jus di birra scura, con canederli o polenta.', 'Tendre rôti de porc à la croûte croustillante et jus de bière brune, accompagné de quenelles ou de polenta.', 'ca. € 19,90', 'ca. € 19,90', 'ca. € 19,90', 'ca. € 19,90', 1);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Rinderbraten', 'Rinderbraten', 'Rinderbraten', 'Rinderbraten', 'Saftiger Rinderbraten mit italienischem Twist – geschmort, aromatisch, mit Beilage.', 'Juicy Rinderbraten with an Italian twist – braised, aromatic, with a side.', 'Succoso Rinderbraten con un tocco italiano – brasato, aromatico, con contorno.', 'Rôti de bœuf juteux avec une touche italienne – braisé, aromatique, avec garniture.', 'ca. € 22,90', 'ca. € 22,90', 'ca. € 22,90', 'ca. € 22,90', 2);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Bavarese vegetarisch', 'Bavarese vegetarian', 'Bavarese vegetariano', 'Bavarese végétarien', 'Herzhaft-vegetarische Variante mit Käse und bayerisch-italienischen Beilagen.', 'A hearty vegetarian version with cheese and Bavarian-Italian sides.', 'Variante vegetariana saporita con formaggio e contorni bavaresi-italiani.', 'Variante végétarienne savoureuse au fromage et garnitures bavaroises-italiennes.', 'ca. € 16,90', 'ca. € 16,90', 'ca. € 16,90', 'ca. € 16,90', 3);

  INSERT INTO public.menu_categories (menu_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, sort_order)
  VALUES (m_id, 'Gruppen- & Firmen-Pakete', 'Group & company packages', 'Pacchetti gruppi & aziende', 'Formules groupes & entreprises', 'Planbar feiern: Wählt ein Paket für eure Gruppe – wir stellen Brotzeit, Bier und Hauptgang zusammen.', 'Celebrate with a plan: choose a package for your group – we put together Brotzeit, beer and main course.', 'Festeggiate in modo programmabile: scegliete un pacchetto per il vostro gruppo – noi componiamo Brotzeit, birra e secondo.', 'Fêtez en toute sérénité: choisissez une formule pour votre groupe – nous composons brotzeit, bière et plat principal.', 6)
  RETURNING id INTO c_id;
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Wiesn-Brotzeit', 'Wiesn Brotzeit', 'Brotzeit della Wiesn', 'Brotzeit de la Wiesn', 'Bavarese-Brett zum Teilen, Brezn und eine Maß Wiesnbier vom Holzfass pro Person – der gemütliche Einstieg.', 'Bavarese board to share, Brezn (pretzels) and one Maß of Wiesnbier from the wooden cask per person – the cosy entry point.', 'Tagliere Bavarese da condividere, Brezn (bretzel) e una Maß di Wiesnbier (birra dell''Oktoberfest) dalla botte di legno a persona – l''inizio accogliente.', 'Planche Bavarese à partager, Brezn et une Maß de bière de la Wiesn au fût de bois par personne – l''entrée en matière conviviale.', 'ab ca. € 29 p. P.', 'from approx. € 29 p.p.', 'da circa € 29 a persona', 'à partir d''env. € 29 p. pers.', 1);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Bavarese-Gruppenmenü', 'Bavarese group menu', 'Menù di gruppo Bavarese', 'Menu de groupe Bavarese', 'Brotzeit zum Teilen, Special-Pizza oder Braten als Hauptgang und ein Bier – ideal ab 8 Personen.', 'Brotzeit to share, special pizza or roast as a main course and a beer – ideal from 8 people.', 'Brotzeit da condividere, pizza speciale o arrosto come secondo e una birra – ideale da 8 persone.', 'Brotzeit à partager, pizza spéciale ou rôti en plat principal et une bière – idéal à partir de 8 personnes.', 'ab ca. € 39 p. P.', 'from approx. € 39 p.p.', 'da circa € 39 a persona', 'à partir d''env. € 39 p. pers.', 2);
  INSERT INTO public.menu_items (category_id, name, name_en, name_it, name_fr, description, description_en, description_it, description_fr, price_display, price_display_en, price_display_it, price_display_fr, sort_order)
  VALUES (c_id, 'Firmen-Wiesn-Paket', 'Company Wiesn package', 'Pacchetto Wiesn aziendale', 'Formule Wiesn entreprise', 'Individuell für euer Team: Brotzeit, Hauptgang, Getränkepauschale und reservierter Bereich – auf Anfrage.', 'Tailored to your team: Brotzeit, main course, drinks flat rate and a reserved area – on request.', 'Su misura per il vostro team: Brotzeit, secondo, forfait bevande e area riservata – su richiesta.', 'Sur mesure pour votre équipe: brotzeit, plat principal, forfait boissons et espace réservé – sur demande.', 'auf Anfrage', 'on request', 'su richiesta', 'sur demande', 3);
END $$;
