// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Guard: wenn Env-Vars nicht gesetzt (z.B. CI ohne Secrets), nicht crashen.
// SSG-Seiten nutzen React-Query-Hydration und brauchen keinen Live-Client.
function createSupabaseClient(): SupabaseClient<Database> | null {
  try {
    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) return null;
    new URL(SUPABASE_URL); // URL-Validierung vor createClient
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } catch (e) {
    console.warn('[Supabase] Client nicht initialisiert (fehlende Env-Vars):', e);
    return null;
  }
}

export const supabase = createSupabaseClient() as SupabaseClient<Database>;